# Local console build override
# Use with: docker compose -f docker-compose.yml -f docker-compose.local-console.yml up -d --build

name: ledger

services:
  console:
    build:
      context: .
      dockerfile: ./Dockerfile.console
    image: console-local:latest
